### PR TITLE
fix more

### PR DESCRIPTION
**Pull request by ghost**
Probably fix bug: If start arena, get new color instantly

### CODE REVIEW

**Comment by ghost** [comment]
@Creeperface01

**Comment by ghost** [comment]
@Creeperface01 Accept?

**Review by Creeperface01 — COMMENTED** [review]
Its wrong

**Comment by ghost** [comment]
@Creeperface01 https://github.com/Creeperface01/ColorMatch/pull/22/commits/7998506be3b91c369ff6bcf642ca45c408221f22

Probably fix with this commit

**Comment by ghost** [comment]
startTime = 0 ...

**Comment by ghost** [comment]
@creeperface01 Accept or close?

**Pull request closed without merging**
